// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userinfo.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_Idel Gender = 0
	Gender_Boy  Gender = 1
	Gender_Girl Gender = 2
)

var Gender_name = map[int32]string{
	0: "Idel",
	1: "Boy",
	2: "Girl",
}

var Gender_value = map[string]int32{
	"Idel": 0,
	"Boy":  1,
	"Girl": 2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_785a78c34699a93d, []int{0}
}

type UMap struct {
	Map                  map[string]string `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UMap) Reset()         { *m = UMap{} }
func (m *UMap) String() string { return proto.CompactTextString(m) }
func (*UMap) ProtoMessage()    {}
func (*UMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_785a78c34699a93d, []int{0}
}

func (m *UMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UMap.Unmarshal(m, b)
}
func (m *UMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UMap.Marshal(b, m, deterministic)
}
func (m *UMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UMap.Merge(m, src)
}
func (m *UMap) XXX_Size() int {
	return xxx_messageInfo_UMap.Size(m)
}
func (m *UMap) XXX_DiscardUnknown() {
	xxx_messageInfo_UMap.DiscardUnknown(m)
}

var xxx_messageInfo_UMap proto.InternalMessageInfo

func (m *UMap) GetMap() map[string]string {
	if m != nil {
		return m.Map
	}
	return nil
}

type UserInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender               Gender   `protobuf:"varint,2,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_785a78c34699a93d, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_Idel
}

func (m *UserInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type RegisterUserReq struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterUserReq) Reset()         { *m = RegisterUserReq{} }
func (m *RegisterUserReq) String() string { return proto.CompactTextString(m) }
func (*RegisterUserReq) ProtoMessage()    {}
func (*RegisterUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_785a78c34699a93d, []int{2}
}

func (m *RegisterUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserReq.Unmarshal(m, b)
}
func (m *RegisterUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserReq.Marshal(b, m, deterministic)
}
func (m *RegisterUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserReq.Merge(m, src)
}
func (m *RegisterUserReq) XXX_Size() int {
	return xxx_messageInfo_RegisterUserReq.Size(m)
}
func (m *RegisterUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserReq proto.InternalMessageInfo

func (m *RegisterUserReq) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterUserRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserID               int64    `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRsp) Reset()         { *m = RegisterUserRsp{} }
func (m *RegisterUserRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRsp) ProtoMessage()    {}
func (*RegisterUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_785a78c34699a93d, []int{3}
}

func (m *RegisterUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRsp.Unmarshal(m, b)
}
func (m *RegisterUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRsp.Marshal(b, m, deterministic)
}
func (m *RegisterUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRsp.Merge(m, src)
}
func (m *RegisterUserRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRsp.Size(m)
}
func (m *RegisterUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRsp proto.InternalMessageInfo

func (m *RegisterUserRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterUserRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RegisterUserRsp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserInfoReq struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_785a78c34699a93d, []int{4}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

func (m *GetUserInfoReq) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserInfoRsp struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserInfoRsp) Reset()         { *m = GetUserInfoRsp{} }
func (m *GetUserInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRsp) ProtoMessage()    {}
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_785a78c34699a93d, []int{5}
}

func (m *GetUserInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRsp.Unmarshal(m, b)
}
func (m *GetUserInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRsp.Merge(m, src)
}
func (m *GetUserInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRsp.Size(m)
}
func (m *GetUserInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRsp proto.InternalMessageInfo

func (m *GetUserInfoRsp) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("user.Gender", Gender_name, Gender_value)
	proto.RegisterType((*UMap)(nil), "user.UMap")
	proto.RegisterMapType((map[string]string)(nil), "user.UMap.MapEntry")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*RegisterUserReq)(nil), "user.RegisterUserReq")
	proto.RegisterType((*RegisterUserRsp)(nil), "user.RegisterUserRsp")
	proto.RegisterType((*GetUserInfoReq)(nil), "user.GetUserInfoReq")
	proto.RegisterType((*GetUserInfoRsp)(nil), "user.GetUserInfoRsp")
}

func init() { proto.RegisterFile("userinfo.proto", fileDescriptor_785a78c34699a93d) }

var fileDescriptor_785a78c34699a93d = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0xcb, 0xd3, 0x40,
	0x10, 0xc6, 0xdd, 0xe6, 0xc3, 0x38, 0x79, 0x89, 0x61, 0x7d, 0x95, 0xd0, 0x53, 0x09, 0x16, 0x82,
	0x87, 0x08, 0xf1, 0x03, 0x15, 0x4f, 0x45, 0x29, 0x3d, 0x14, 0x61, 0xa5, 0x17, 0x6f, 0xd1, 0x4c,
	0x63, 0xb1, 0x4d, 0xb6, 0xbb, 0x69, 0xa1, 0x37, 0x4f, 0xfe, 0xdd, 0x32, 0xbb, 0xa9, 0xa4, 0xa5,
	0x07, 0x6f, 0xcf, 0x3c, 0xb3, 0x33, 0xf3, 0x9b, 0x49, 0x20, 0x3a, 0x68, 0x54, 0x9b, 0x66, 0xdd,
	0xe6, 0x52, 0xb5, 0x5d, 0xcb, 0x5d, 0x8a, 0x53, 0x04, 0x77, 0xb5, 0x2c, 0x25, 0x9f, 0x82, 0xb3,
	0x2b, 0x65, 0xc2, 0x26, 0x4e, 0x16, 0x16, 0x4f, 0x72, 0xca, 0xe5, 0x94, 0xc8, 0x97, 0xa5, 0xfc,
	0xdc, 0x74, 0xea, 0x24, 0x28, 0x3f, 0x7e, 0x0b, 0xc1, 0xd9, 0xe0, 0x31, 0x38, 0xbf, 0xf0, 0x94,
	0xb0, 0x09, 0xcb, 0x1e, 0x09, 0x92, 0xfc, 0x1e, 0xbc, 0x63, 0xb9, 0x3d, 0x60, 0x32, 0x32, 0x9e,
	0x0d, 0x3e, 0x8c, 0xde, 0xb1, 0xf4, 0x37, 0x83, 0x60, 0xa5, 0x51, 0x2d, 0x9a, 0x75, 0xcb, 0x39,
	0xb8, 0x4d, 0xb9, 0xc3, 0xbe, 0xd2, 0x68, 0xfe, 0x1c, 0xfc, 0x1a, 0x9b, 0x0a, 0x95, 0xa9, 0x8d,
	0x8a, 0x3b, 0x8b, 0x30, 0x37, 0x9e, 0xe8, 0x73, 0x34, 0xb2, 0xac, 0x31, 0x71, 0x26, 0x2c, 0xf3,
	0x04, 0x49, 0xea, 0x55, 0x56, 0x95, 0x4a, 0x5c, 0xdb, 0x8b, 0x34, 0x61, 0xc8, 0x9f, 0x6d, 0x83,
	0x89, 0x67, 0x31, 0x4c, 0x90, 0xbe, 0x81, 0xc7, 0x02, 0xeb, 0x8d, 0xee, 0x50, 0x11, 0x89, 0xc0,
	0x3d, 0x4f, 0xc1, 0x1c, 0xc1, 0x80, 0x84, 0x45, 0xd4, 0x6f, 0xdd, 0x63, 0x0a, 0x7b, 0xa0, 0x2f,
	0x57, 0x65, 0x5a, 0xd2, 0xcc, 0x1f, 0x6d, 0x65, 0xf9, 0x3d, 0x61, 0x34, 0x91, 0xed, 0x74, 0xdd,
	0x2f, 0x4e, 0x92, 0x3f, 0x03, 0x9f, 0x1a, 0x2c, 0x3e, 0x19, 0x5c, 0x47, 0xf4, 0x51, 0x9a, 0x41,
	0x34, 0xc7, 0xee, 0xdf, 0x14, 0xdc, 0x0f, 0x5e, 0xb2, 0x8b, 0x97, 0xaf, 0x2f, 0x5f, 0x6a, 0xf9,
	0x3f, 0xc0, 0x2f, 0xa6, 0xe0, 0xdb, 0xab, 0xf1, 0x00, 0xdc, 0x45, 0x85, 0xdb, 0xf8, 0x01, 0x7f,
	0x08, 0xce, 0xac, 0x3d, 0xc5, 0x8c, 0xac, 0xf9, 0x46, 0x6d, 0xe3, 0x51, 0xf1, 0x87, 0x41, 0x78,
	0xae, 0xfc, 0x7a, 0x54, 0xfc, 0x23, 0xdc, 0x0d, 0xf7, 0xe4, 0x4f, 0x6d, 0xf3, 0xab, 0x93, 0x8d,
	0x6f, 0xd9, 0x5a, 0xf2, 0xf7, 0x10, 0x0e, 0x50, 0xf9, 0xfd, 0xf9, 0xeb, 0x0d, 0xf7, 0x1c, 0xdf,
	0x70, 0xb5, 0x9c, 0x05, 0xdf, 0xfc, 0xfc, 0x25, 0x25, 0xbe, 0xfb, 0xe6, 0xc7, 0x7c, 0xf5, 0x37,
	0x00, 0x00, 0xff, 0xff, 0xf2, 0xc0, 0xcf, 0x26, 0xaa, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserInfoSvrClient is the client API for UserInfoSvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserInfoSvrClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserRsp, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRsp, error)
}

type userInfoSvrClient struct {
	cc *grpc.ClientConn
}

func NewUserInfoSvrClient(cc *grpc.ClientConn) UserInfoSvrClient {
	return &userInfoSvrClient{cc}
}

func (c *userInfoSvrClient) RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserRsp, error) {
	out := new(RegisterUserRsp)
	err := c.cc.Invoke(ctx, "/user.UserInfoSvr/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInfoSvrClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRsp, error) {
	out := new(GetUserInfoRsp)
	err := c.cc.Invoke(ctx, "/user.UserInfoSvr/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInfoSvrServer is the server API for UserInfoSvr service.
type UserInfoSvrServer interface {
	RegisterUser(context.Context, *RegisterUserReq) (*RegisterUserRsp, error)
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoRsp, error)
}

// UnimplementedUserInfoSvrServer can be embedded to have forward compatible implementations.
type UnimplementedUserInfoSvrServer struct {
}

func (*UnimplementedUserInfoSvrServer) RegisterUser(ctx context.Context, req *RegisterUserReq) (*RegisterUserRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedUserInfoSvrServer) GetUserInfo(ctx context.Context, req *GetUserInfoReq) (*GetUserInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}

func RegisterUserInfoSvrServer(s *grpc.Server, srv UserInfoSvrServer) {
	s.RegisterService(&_UserInfoSvr_serviceDesc, srv)
}

func _UserInfoSvr_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoSvrServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserInfoSvr/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoSvrServer).RegisterUser(ctx, req.(*RegisterUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInfoSvr_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoSvrServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserInfoSvr/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoSvrServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInfoSvr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserInfoSvr",
	HandlerType: (*UserInfoSvrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserInfoSvr_RegisterUser_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _UserInfoSvr_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userinfo.proto",
}
